### ISSUE TITLE
Lincese for Modpack

### ISSUE THREAD

**Issue by endercraftm** [yoskaz01/ccSensors#1]
Hi!
I'm making a modpack for 1.2.5 version and i want to use your mod CC Sensors in my pack, would you mind if i used it?
Here is the version of mod that i'm using

[ccSensors-client-MC125-B017pr2.zip](https://github.com/yoskaz01/ccSensors/files/12328032/ccSensors-client-MC125-B017pr2.zip)

**Comment by yosiz** [comment]
Yea sure,
Just be aware its kinda old and not upated

**Comment by endercraftm** [comment]
Thank you very much =)
